### ISSUE TITLE
Build images with single file in `push_docker_image` workflow

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.Headless#2609]
## Overview

Please make `push_docker_image` to build `linux/arm64` and `linux/amd64` image with single dockerfile.

The following links will be helpful when working on this issue:

 - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
 - https://github.com/docker/setup-buildx-action
 - https://github.com/docker/build-push-action

## 🙌🏻  Context

Now, there are `Dockerfile.amd64` and `Dockerfile.arm64v8` files to build for each platforms.

https://github.com/planetarium/NineChronicles.Headless/blob/c879bd5d8d8730b27547b11a93d210a811db8dab/.github/workflows/push_docker_image.yml#L51-L66

But there are no difference between two dockerfiles and `docker buildx build --platforms linux/amd64,linux/arm64` command can the two platforms at once.

```yaml
# https://github.com/planetarium/mimir/blob/2ce505fb86f0dac98ffed16d30581371555a85e3/.github/workflows/docker.yaml
-
  name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3
  with:
    platforms: linux/arm/v8,linux/amd64
-
  name: Build and push
  uses: docker/build-push-action@v5
  with:
    push: ${{ github.event_name != 'pull_request' }}
    platforms: linux/arm64,linux/amd64
    tags: ${{ matrix.docker.repo }}:git-${{ github.sha }}
    file: ${{ matrix.docker.dockerfile }}
```

Since https://github.com/planetarium/NineChronicles.Headless/pull/2599, `Dockerfile` and `Dockerfile.Acc` are now able to build both linux/arm64 and linux/amd64. But I missed to make the [`push_docker_image` workflow](https://github.com/planetarium/NineChronicles.Headless/blob/c879bd5d8d8730b27547b11a93d210a811db8dab/.github/workflows/push_docker_image.yml) to build images with the `Dockerfile` and `Dockerfile.Acc` file.

So this issue suggests to fix the missed work.
